theme: jekyll-theme-cayman
# Site settings
title: 北冥有鱼溜达鸡    				  	#你博客的标题
SEOTitle: 北冥有鱼溜达鸡 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: kyd.freedom@gmail.com	
description: "北冥有鱼溜达鸡的地方"  			 #网站介绍
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone" #关键词
url: "https://qiubaiying.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
