theme: jekyll-theme-cayman
# Site settings
title: 北冥有鱼溜达鸡    				  	#你博客的标题
SEOTitle: 北冥有鱼溜达鸡 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: kyd.freedom@gmail.com	
description: "北冥有鱼溜达鸡的地方"  			 #网站介绍
keyword: "党堃原的博客, dangkunyuan, 北冥有鱼溜达鸡, 区块链, blockchain" #关键词
url: "https://dangkunyuan.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "我就喜欢溜达鸡"
sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g

